CREATE TABLE IF NOT EXISTS employees (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_code VARCHAR(50) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  department VARCHAR(100),
  position VARCHAR(100),
  shift VARCHAR(20) NOT NULL DEFAULT 'day',
  date_hired DATE,
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (employee_code)
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(150) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'employee',
  employee_id INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (email),
  CONSTRAINT fk_users_employee_id FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS leave_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  default_credits INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leave_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL,
  employee_code VARCHAR(50),
  employee_name VARCHAR(200),
  leave_type_id INTEGER NOT NULL,
  leave_type_name VARCHAR(100),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT,
  status VARCHAR(20) DEFAULT 'pending',
  approved_by INTEGER NULL,
  approved_by_name VARCHAR(150),
  approved_by_role VARCHAR(50),
  rejection_comment TEXT,
  attachment_name VARCHAR(255),
  attachment_type VARCHAR(100),
  attachment_data TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_leave_requests_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  CONSTRAINT fk_leave_requests_type FOREIGN KEY (leave_type_id) REFERENCES leave_types(id) ON DELETE RESTRICT
);

-- Optional: allow cancellations (if you choose to enforce a check constraint later)
-- This project uses a free-form status field; no DB constraint needed.

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  action VARCHAR(100) NOT NULL,
  target_table VARCHAR(100) NOT NULL,
  target_id INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name VARCHAR(200) NOT NULL,
  contact_name VARCHAR(150) NOT NULL,
  email VARCHAR(200) NOT NULL,
  phone VARCHAR(60),
  source VARCHAR(60),
  status VARCHAR(40) DEFAULT 'new',
  interested_services JSONB DEFAULT '[]'::jsonb,
  estimated_value NUMERIC(12,2) DEFAULT 0,
  next_follow_up DATE,
  notes TEXT,
  converted_client_id INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lead_conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id INTEGER NOT NULL,
  type VARCHAR(40) DEFAULT 'other',
  happened_at TIMESTAMPTZ DEFAULT NOW(),
  summary TEXT NOT NULL,
  outcome TEXT,
  created_by INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_lead_conversations_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_lead_conversations_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS clients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id INTEGER NULL,
  company_name VARCHAR(200) NOT NULL,
  contact_name VARCHAR(150) NOT NULL,
  email VARCHAR(200) NOT NULL,
  phone VARCHAR(60),
  package_name VARCHAR(80) DEFAULT 'custom',
  monthly_value NUMERIC(12,2) DEFAULT 0,
  package_details TEXT,
  services JSONB DEFAULT '[]'::jsonb,
  contract_start_date DATE,
  contract_end_date DATE,
  address TEXT,
  status VARCHAR(40) DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_clients_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL
);
