CREATE TABLE IF NOT EXISTS employees (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_code VARCHAR(50) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  department VARCHAR(100),
  position VARCHAR(100),
  shift VARCHAR(20) NOT NULL DEFAULT 'day',
  leave_credits NUMERIC(10,2) NOT NULL DEFAULT 0,
  date_hired DATE,
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (employee_code)
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(150) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'employee',
  employee_id INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (email),
  CONSTRAINT fk_users_employee_id FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS leave_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL,
  employee_code VARCHAR(50),
  employee_name VARCHAR(200),
  leave_type_name VARCHAR(100),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT,
  status VARCHAR(20) DEFAULT 'pending',
  leave_pay_type VARCHAR(20) NOT NULL DEFAULT 'unpaid',
  leave_days NUMERIC(10,2) NOT NULL DEFAULT 0,
  credits_deducted NUMERIC(10,2) NOT NULL DEFAULT 0,
  approved_by INTEGER NULL,
  approved_by_name VARCHAR(150),
  approved_by_role VARCHAR(50),
  rejection_comment TEXT,
  attachment_name VARCHAR(255),
  attachment_type VARCHAR(100),
  attachment_data TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_leave_requests_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

-- Optional: allow cancellations (if you choose to enforce a check constraint later)
-- This project uses a free-form status field; no DB constraint needed.

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  action VARCHAR(100) NOT NULL,
  target_table VARCHAR(100) NOT NULL,
  target_id INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name VARCHAR(200) NOT NULL,
  contact_name VARCHAR(150) NOT NULL,
  email VARCHAR(200) NOT NULL,
  phone VARCHAR(60),
  source VARCHAR(60),
  status VARCHAR(40) DEFAULT 'new',
  interested_services JSONB DEFAULT '[]'::jsonb,
  estimated_value NUMERIC(12,2) DEFAULT 0,
  next_follow_up DATE,
  notes TEXT,
  converted_client_id INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lead_conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id INTEGER NOT NULL,
  type VARCHAR(40) DEFAULT 'other',
  happened_at TIMESTAMPTZ DEFAULT NOW(),
  summary TEXT NOT NULL,
  outcome TEXT,
  created_by INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_lead_conversations_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_lead_conversations_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS clients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id INTEGER NULL,
  company_name VARCHAR(200) NOT NULL,
  contact_name VARCHAR(150) NOT NULL,
  email VARCHAR(200) NOT NULL,
  phone VARCHAR(60),
  package_name VARCHAR(80) DEFAULT 'custom',
  monthly_value NUMERIC(12,2) DEFAULT 0,
  package_details TEXT,
  services JSONB DEFAULT '[]'::jsonb,
  contract_start_date DATE,
  contract_end_date DATE,
  address TEXT,
  notes TEXT,
  status VARCHAR(40) DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_clients_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS client_conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER NOT NULL,
  type VARCHAR(40) DEFAULT 'other',
  happened_at TIMESTAMPTZ DEFAULT NOW(),
  summary TEXT NOT NULL,
  outcome TEXT,
  created_by INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_client_conversations_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT fk_client_conversations_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS services (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER NOT NULL,
  service_type VARCHAR(60) NOT NULL,
  status VARCHAR(40) DEFAULT 'not_started',
  assigned_user_ids JSONB DEFAULT '[]'::jsonb,
  platforms JSONB DEFAULT '[]'::jsonb,
  website_url TEXT,
  progress INTEGER DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_services_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  client_id INTEGER NULL,
  service_id INTEGER NULL,
  assigned_to INTEGER NOT NULL,
  status VARCHAR(40) DEFAULT 'pending',
  priority VARCHAR(30) DEFAULT 'medium',
  due_date DATE NOT NULL,
  is_automated BOOLEAN DEFAULT FALSE,
  automation_rule_id INTEGER NULL,
  completed_date TIMESTAMPTZ,
  completion_notes TEXT,
  proof_of_work_name VARCHAR(255),
  proof_of_work_type VARCHAR(100),
  proof_of_work_data TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_tasks_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
  CONSTRAINT fk_tasks_service FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL,
  CONSTRAINT fk_tasks_user FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS automation_rules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_name VARCHAR(200) NOT NULL,
  client_id INTEGER NOT NULL,
  service_id INTEGER NULL,
  task_title_template VARCHAR(200) NOT NULL,
  task_description_template TEXT,
  assigned_to INTEGER NOT NULL,
  priority VARCHAR(30) DEFAULT 'medium',
  schedule_type VARCHAR(30) DEFAULT 'daily',
  custom_days JSONB DEFAULT '[]'::jsonb,
  start_date DATE,
  end_date DATE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_automation_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT fk_automation_service FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL,
  CONSTRAINT fk_automation_user FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  type VARCHAR(60) NOT NULL,
  title VARCHAR(200) NOT NULL,
  message TEXT,
  target_table VARCHAR(60),
  target_id INTEGER,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
