CREATE TABLE IF NOT EXISTS employees (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_code VARCHAR(50) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  department VARCHAR(100),
  position VARCHAR(100),
  salary_type VARCHAR(50) DEFAULT 'monthly',
  salary_amount NUMERIC(12,2) DEFAULT 0,
  weekly_allowance NUMERIC(12,2) DEFAULT 0,
  date_hired DATE,
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (employee_code)
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(150) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'employee',
  employee_id INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (email),
  CONSTRAINT fk_users_employee_id FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS leave_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  default_credits INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leave_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL,
  employee_code VARCHAR(50),
  employee_name VARCHAR(200),
  leave_type_id INTEGER NOT NULL,
  leave_type_name VARCHAR(100),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT,
  status VARCHAR(20) DEFAULT 'pending',
  approved_by INTEGER NULL,
  approved_by_name VARCHAR(150),
  approved_by_role VARCHAR(50),
  rejection_comment TEXT,
  attachment_name VARCHAR(255),
  attachment_type VARCHAR(100),
  attachment_data TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_leave_requests_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  CONSTRAINT fk_leave_requests_type FOREIGN KEY (leave_type_id) REFERENCES leave_types(id) ON DELETE RESTRICT
);

-- Optional: allow cancellations (if you choose to enforce a check constraint later)
-- This project uses a free-form status field; no DB constraint needed.

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  action VARCHAR(100) NOT NULL,
  target_table VARCHAR(100) NOT NULL,
  target_id INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payroll_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  status VARCHAR(20) DEFAULT 'finalized',
  created_by INTEGER NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_payroll_runs_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS payroll_payslips (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id INTEGER NOT NULL,
  employee_id INTEGER NOT NULL,
  employee_name VARCHAR(200),
  department VARCHAR(100),
  base_salary NUMERIC(12,2) DEFAULT 0,
  weekly_allowance NUMERIC(12,2) DEFAULT 0,
  allowance_weeks INTEGER DEFAULT 0,
  total_allowance NUMERIC(12,2) DEFAULT 0,
  gross_pay NUMERIC(12,2) DEFAULT 0,
  net_pay NUMERIC(12,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_payslips_run FOREIGN KEY (run_id) REFERENCES payroll_runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_payslips_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);
