CREATE TABLE IF NOT EXISTS leave_request_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  leave_request_id INTEGER NOT NULL REFERENCES leave_requests(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  author_role VARCHAR(20) NOT NULL,
  message TEXT NOT NULL,
  read_by_employee_at TIMESTAMPTZ NULL,
  read_by_management_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leave_request_comments_request_created
  ON leave_request_comments (leave_request_id, created_at ASC);
