CREATE TABLE IF NOT EXISTS leave_change_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  leave_request_id INTEGER NOT NULL REFERENCES leave_requests(id) ON DELETE CASCADE,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  request_type VARCHAR(20) NOT NULL CHECK (request_type IN ('move', 'cancel')),
  original_start_date DATE NOT NULL,
  original_end_date DATE NOT NULL,
  requested_start_date DATE,
  requested_end_date DATE,
  reason TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  review_comment TEXT,
  reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  reviewed_by_name VARCHAR(150),
  reviewed_by_role VARCHAR(50),
  credits_refunded NUMERIC(10,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_leave_change_requests_one_pending
  ON leave_change_requests (leave_request_id)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_leave_change_requests_employee_created
  ON leave_change_requests (employee_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_leave_change_requests_status_created
  ON leave_change_requests (status, created_at ASC);
