CREATE TABLE IF NOT EXISTS philippine_holidays (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  holiday_date DATE NOT NULL UNIQUE,
  name VARCHAR(180) NOT NULL,
  category VARCHAR(40) NOT NULL,
  is_working_day BOOLEAN NOT NULL DEFAULT FALSE,
  source VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_philippine_holidays_date
  ON philippine_holidays (holiday_date);

INSERT INTO philippine_holidays
  (holiday_date, name, category, is_working_day, source)
VALUES
  ('2026-01-01', 'New Year''s Day', 'regular', FALSE, 'Proclamation No. 1006'),
  ('2026-02-17', 'Chinese New Year', 'special_non_working', FALSE, 'Proclamation No. 1006'),
  ('2026-02-25', 'EDSA People Power Revolution Anniversary', 'special_working', TRUE, 'Proclamation No. 1006'),
  ('2026-03-20', 'Eid''l Fitr', 'regular', FALSE, 'Proclamation No. 1189'),
  ('2026-04-02', 'Maundy Thursday', 'regular', FALSE, 'Proclamation No. 1006'),
  ('2026-04-03', 'Good Friday', 'regular', FALSE, 'Proclamation No. 1006'),
  ('2026-04-04', 'Black Saturday', 'special_non_working', FALSE, 'Proclamation No. 1006'),
  ('2026-04-09', 'Araw ng Kagitingan', 'regular', FALSE, 'Proclamation No. 1006'),
  ('2026-05-01', 'Labor Day', 'regular', FALSE, 'Proclamation No. 1006'),
  ('2026-05-27', 'Eid''l Adha', 'regular', FALSE, 'Proclamation No. 1264'),
  ('2026-06-12', 'Independence Day', 'regular', FALSE, 'Proclamation No. 1006'),
  ('2026-08-21', 'Ninoy Aquino Day', 'special_non_working', FALSE, 'Proclamation No. 1006'),
  ('2026-08-31', 'National Heroes Day', 'regular', FALSE, 'Proclamation No. 1006'),
  ('2026-11-01', 'All Saints'' Day', 'special_non_working', FALSE, 'Proclamation No. 1006'),
  ('2026-11-02', 'All Souls'' Day', 'special_non_working', FALSE, 'Proclamation No. 1006'),
  ('2026-11-30', 'Bonifacio Day', 'regular', FALSE, 'Proclamation No. 1006'),
  ('2026-12-08', 'Feast of the Immaculate Conception of Mary', 'special_non_working', FALSE, 'Proclamation No. 1006'),
  ('2026-12-24', 'Christmas Eve', 'special_non_working', FALSE, 'Proclamation No. 1006'),
  ('2026-12-25', 'Christmas Day', 'regular', FALSE, 'Proclamation No. 1006'),
  ('2026-12-30', 'Rizal Day', 'regular', FALSE, 'Proclamation No. 1006'),
  ('2026-12-31', 'Last Day of the Year', 'special_non_working', FALSE, 'Proclamation No. 1006')
ON CONFLICT (holiday_date) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  is_working_day = EXCLUDED.is_working_day,
  source = EXCLUDED.source;

-- Correct existing 2026 records that were originally counted using calendar days.
WITH working_day_counts AS (
  SELECT
    lr.id,
    lr.employee_id,
    lr.status,
    lr.credits_deducted AS old_credits,
    COUNT(*) FILTER (
      WHERE EXTRACT(ISODOW FROM day_value) BETWEEN 1 AND 5
        AND (holiday.id IS NULL OR holiday.is_working_day = TRUE)
    )::numeric AS new_days
  FROM leave_requests lr
  CROSS JOIN LATERAL generate_series(lr.start_date, lr.end_date, INTERVAL '1 day') AS day_value
  LEFT JOIN philippine_holidays holiday ON holiday.holiday_date = day_value::date
  WHERE EXTRACT(YEAR FROM lr.start_date) = 2026
  GROUP BY lr.id, lr.employee_id, lr.status, lr.credits_deducted
),
refunds AS (
  SELECT
    employee_id,
    SUM(GREATEST(0, old_credits - LEAST(old_credits, new_days))) AS credits_to_refund
  FROM working_day_counts
  WHERE status = 'approved'
  GROUP BY employee_id
)
UPDATE employees employee
SET leave_credits = employee.leave_credits + refunds.credits_to_refund,
    updated_at = NOW()
FROM refunds
WHERE employee.id = refunds.employee_id
  AND refunds.credits_to_refund > 0;

WITH working_day_counts AS (
  SELECT
    lr.id,
    COUNT(*) FILTER (
      WHERE EXTRACT(ISODOW FROM day_value) BETWEEN 1 AND 5
        AND (holiday.id IS NULL OR holiday.is_working_day = TRUE)
    )::numeric AS new_days
  FROM leave_requests lr
  CROSS JOIN LATERAL generate_series(lr.start_date, lr.end_date, INTERVAL '1 day') AS day_value
  LEFT JOIN philippine_holidays holiday ON holiday.holiday_date = day_value::date
  WHERE EXTRACT(YEAR FROM lr.start_date) = 2026
  GROUP BY lr.id
),
adjusted AS (
  SELECT
    lr.id,
    counts.new_days,
    LEAST(lr.paid_days, counts.new_days) AS new_paid_days,
    GREATEST(0, counts.new_days - LEAST(lr.paid_days, counts.new_days)) AS new_unpaid_days,
    LEAST(lr.credits_deducted, counts.new_days) AS new_credits
  FROM leave_requests lr
  JOIN working_day_counts counts ON counts.id = lr.id
)
UPDATE leave_requests request
SET leave_days = adjusted.new_days,
    paid_days = adjusted.new_paid_days,
    unpaid_days = adjusted.new_unpaid_days,
    credits_deducted = adjusted.new_credits,
    leave_pay_type = CASE
      WHEN adjusted.new_paid_days <= 0 THEN 'unpaid'
      WHEN adjusted.new_unpaid_days <= 0 THEN 'paid'
      ELSE 'partial_paid'
    END
FROM adjusted
WHERE request.id = adjusted.id;
