CREATE TABLE IF NOT EXISTS hr_calendar_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_type VARCHAR(20) NOT NULL CHECK (entry_type IN ('leave', 'note')),
  employee_id INTEGER REFERENCES employees(id) ON DELETE SET NULL,
  title VARCHAR(160) NOT NULL,
  leave_type_name VARCHAR(120),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  description VARCHAR(500),
  is_employee_visible BOOLEAN NOT NULL DEFAULT FALSE,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT hr_calendar_entries_valid_range CHECK (end_date >= start_date),
  CONSTRAINT hr_calendar_entries_leave_employee CHECK (
    entry_type <> 'leave' OR employee_id IS NOT NULL
  ),
  CONSTRAINT hr_calendar_entries_leave_type CHECK (
    entry_type <> 'leave' OR COALESCE(BTRIM(leave_type_name), '') <> ''
  )
);

CREATE INDEX IF NOT EXISTS idx_hr_calendar_entries_dates
  ON hr_calendar_entries (start_date, end_date);

CREATE INDEX IF NOT EXISTS idx_hr_calendar_entries_employee
  ON hr_calendar_entries (employee_id, start_date);

-- Migration 016 may already be marked as applied in an existing deployment.
-- Re-upsert the confirmed 2026 regular holiday so every environment receives it.
INSERT INTO philippine_holidays
  (holiday_date, name, category, is_working_day, source)
VALUES
  ('2026-08-31', 'National Heroes Day', 'regular', FALSE, 'Proclamation No. 1006')
ON CONFLICT (holiday_date) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  is_working_day = EXCLUDED.is_working_day,
  source = EXCLUDED.source;
