CREATE TABLE IF NOT EXISTS payroll_employee_profiles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  effective_from DATE NOT NULL,
  effective_to DATE,
  monthly_basic_salary NUMERIC(12,2) NOT NULL CHECK (monthly_basic_salary >= 0),
  daily_fare_rate NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (daily_fare_rate >= 0),
  work_start_time TIME NOT NULL DEFAULT '09:00',
  work_end_time TIME NOT NULL DEFAULT '18:00',
  unpaid_break_minutes INTEGER NOT NULL DEFAULT 60 CHECK (unpaid_break_minutes >= 0),
  workdays SMALLINT[] NOT NULL DEFAULT ARRAY[1,2,3,4,5]::SMALLINT[],
  daily_rate_divisor NUMERIC(8,2) NOT NULL DEFAULT 261 CHECK (daily_rate_divisor > 0),
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (employee_id, effective_from),
  CHECK (effective_to IS NULL OR effective_to >= effective_from),
  CHECK (work_end_time > work_start_time)
);

CREATE INDEX IF NOT EXISTS idx_payroll_profiles_employee_effective
  ON payroll_employee_profiles (employee_id, effective_from DESC, effective_to);

CREATE TABLE IF NOT EXISTS payroll_attendance_import_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name VARCHAR(255),
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  imported_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'imported'
    CHECK (status IN ('imported', 'has_errors')),
  row_count INTEGER NOT NULL DEFAULT 0,
  error_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (period_end >= period_start)
);

CREATE TABLE IF NOT EXISTS payroll_attendance_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id INTEGER NOT NULL REFERENCES payroll_attendance_import_batches(id) ON DELETE CASCADE,
  source_row INTEGER NOT NULL,
  employee_id INTEGER REFERENCES employees(id) ON DELETE SET NULL,
  employee_code VARCHAR(80) NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  source_timestamp TEXT NOT NULL,
  raw_row JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (batch_id, source_row)
);

CREATE INDEX IF NOT EXISTS idx_payroll_attendance_events_batch_employee_time
  ON payroll_attendance_events (batch_id, employee_id, occurred_at);

CREATE TABLE IF NOT EXISTS payroll_attendance_import_errors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id INTEGER NOT NULL REFERENCES payroll_attendance_import_batches(id) ON DELETE CASCADE,
  source_row INTEGER NOT NULL,
  employee_code VARCHAR(80),
  error TEXT NOT NULL,
  raw_row JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (batch_id, source_row)
);

CREATE TABLE IF NOT EXISTS payroll_daily_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id INTEGER NOT NULL REFERENCES payroll_attendance_import_batches(id) ON DELETE CASCADE,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  work_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL CHECK (status IN ('present', 'absent', 'paid_leave', 'unpaid_leave', 'partial_leave', 'exception')),
  first_scan_at TIMESTAMPTZ,
  last_scan_at TIMESTAMPTZ,
  scan_count INTEGER NOT NULL DEFAULT 0 CHECK (scan_count >= 0),
  late_minutes NUMERIC(8,2) NOT NULL DEFAULT 0 CHECK (late_minutes >= 0),
  undertime_minutes NUMERIC(8,2) NOT NULL DEFAULT 0 CHECK (undertime_minutes >= 0),
  exception_reason TEXT,
  leave_deduction_fraction NUMERIC(4,3) NOT NULL DEFAULT 1 CHECK (leave_deduction_fraction BETWEEN 0 AND 1),
  correction_reason TEXT,
  corrected_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  corrected_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (batch_id, employee_id, work_date),
  CHECK (
    (status IN ('absent', 'paid_leave', 'unpaid_leave', 'partial_leave') AND first_scan_at IS NULL AND last_scan_at IS NULL)
    OR (status IN ('present', 'exception') AND first_scan_at IS NOT NULL AND last_scan_at IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_payroll_daily_attendance_batch_date
  ON payroll_daily_attendance (batch_id, work_date, employee_id);

CREATE TABLE IF NOT EXISTS payroll_attendance_corrections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  daily_attendance_id BIGINT NOT NULL REFERENCES payroll_daily_attendance(id) ON DELETE CASCADE,
  previous_status VARCHAR(20) NOT NULL,
  previous_time_in TIMESTAMPTZ,
  previous_time_out TIMESTAMPTZ,
  corrected_status VARCHAR(20) NOT NULL,
  corrected_time_in TIMESTAMPTZ,
  corrected_time_out TIMESTAMPTZ,
  reason TEXT NOT NULL,
  actor_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  actor_role VARCHAR(30),
  actor_name VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION prevent_payroll_attendance_correction_changes()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'Payroll attendance corrections are append-only';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS payroll_attendance_corrections_append_only ON payroll_attendance_corrections;
CREATE TRIGGER payroll_attendance_corrections_append_only
  BEFORE UPDATE OR DELETE ON payroll_attendance_corrections
  FOR EACH ROW EXECUTE FUNCTION prevent_payroll_attendance_correction_changes();

CREATE TABLE IF NOT EXISTS payroll_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  attendance_cutoff DATE,
  payday DATE NOT NULL,
  cutoff VARCHAR(12) NOT NULL CHECK (cutoff IN ('first', 'second')),
  attendance_batch_id INTEGER REFERENCES payroll_attendance_import_batches(id) ON DELETE RESTRICT,
  status VARCHAR(12) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved', 'locked')),
  include_contributions BOOLEAN NOT NULL DEFAULT FALSE,
  rule_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  approved_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  locked_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  locked_at TIMESTAMPTZ,
  CHECK (period_end >= period_start),
  UNIQUE (period_start, period_end, cutoff)
);

CREATE INDEX IF NOT EXISTS idx_payroll_runs_payday_status
  ON payroll_runs (payday DESC, status);

CREATE TABLE IF NOT EXISTS payroll_run_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_run_id INTEGER NOT NULL REFERENCES payroll_runs(id) ON DELETE CASCADE,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
  employee_code VARCHAR(50) NOT NULL,
  employee_name VARCHAR(201) NOT NULL,
  monthly_basic_salary NUMERIC(12,2) NOT NULL,
  daily_rate NUMERIC(12,6) NOT NULL,
  hourly_rate NUMERIC(12,6) NOT NULL,
  gross_salary NUMERIC(12,2) NOT NULL,
  absence_days NUMERIC(8,2) NOT NULL DEFAULT 0,
  paid_leave_days NUMERIC(8,2) NOT NULL DEFAULT 0,
  unpaid_leave_days NUMERIC(8,2) NOT NULL DEFAULT 0,
  absence_deduction NUMERIC(12,2) NOT NULL DEFAULT 0,
  undertime_minutes NUMERIC(10,2) NOT NULL DEFAULT 0,
  undertime_deduction NUMERIC(12,2) NOT NULL DEFAULT 0,
  employee_sss NUMERIC(12,2) NOT NULL DEFAULT 0,
  employer_sss NUMERIC(12,2) NOT NULL DEFAULT 0,
  employer_ec NUMERIC(12,2) NOT NULL DEFAULT 0,
  employee_philhealth NUMERIC(12,2) NOT NULL DEFAULT 0,
  employer_philhealth NUMERIC(12,2) NOT NULL DEFAULT 0,
  employee_pagibig NUMERIC(12,2) NOT NULL DEFAULT 0,
  employer_pagibig NUMERIC(12,2) NOT NULL DEFAULT 0,
  weekly_fare_allowance NUMERIC(12,2) NOT NULL DEFAULT 0,
  thirteenth_month_accrual NUMERIC(12,2) NOT NULL DEFAULT 0,
  net_pay NUMERIC(12,2) NOT NULL,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (payroll_run_id, employee_id)
);

CREATE INDEX IF NOT EXISTS idx_payroll_run_lines_employee_run
  ON payroll_run_lines (employee_id, payroll_run_id DESC);

CREATE TABLE IF NOT EXISTS payroll_run_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payroll_run_id INTEGER NOT NULL REFERENCES payroll_runs(id) ON DELETE CASCADE,
  action VARCHAR(40) NOT NULL,
  actor_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  actor_role VARCHAR(30),
  actor_name VARCHAR(255),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payroll_run_events_run_created
  ON payroll_run_events (payroll_run_id, created_at);

CREATE OR REPLACE FUNCTION prevent_final_payroll_line_changes()
RETURNS TRIGGER AS $$
DECLARE
  run_status VARCHAR(12);
BEGIN
  IF TG_OP <> 'INSERT' THEN
    SELECT status INTO run_status FROM payroll_runs WHERE id = OLD.payroll_run_id;
    IF run_status IS DISTINCT FROM 'draft' THEN
      RAISE EXCEPTION 'Payroll lines may only be changed while the payroll run is draft';
    END IF;
  END IF;

  IF TG_OP <> 'DELETE' THEN
    SELECT status INTO run_status FROM payroll_runs WHERE id = NEW.payroll_run_id;
    IF run_status IS DISTINCT FROM 'draft' THEN
      RAISE EXCEPTION 'Payroll lines may only be changed while the payroll run is draft';
    END IF;
    RETURN NEW;
  END IF;

  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS payroll_run_lines_draft_only ON payroll_run_lines;
CREATE TRIGGER payroll_run_lines_draft_only
  BEFORE INSERT OR UPDATE OR DELETE ON payroll_run_lines
  FOR EACH ROW EXECUTE FUNCTION prevent_final_payroll_line_changes();

CREATE OR REPLACE FUNCTION prevent_final_payroll_run_changes()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Payroll runs are retained for audit history';
  END IF;

  IF OLD.status = 'locked' THEN
    RAISE EXCEPTION 'Locked payroll runs are immutable';
  END IF;

  IF OLD.status <> NEW.status AND NOT (
    (OLD.status = 'draft' AND NEW.status = 'approved')
    OR (OLD.status = 'approved' AND NEW.status = 'locked')
  ) THEN
    RAISE EXCEPTION 'Invalid payroll run status transition';
  END IF;

  IF OLD.status = 'draft' AND NEW.status = 'approved'
     AND (to_jsonb(NEW) - ARRAY['status', 'approved_by', 'approved_at'])
       IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['status', 'approved_by', 'approved_at']) THEN
    RAISE EXCEPTION 'Approval may only change payroll status and approval metadata';
  END IF;

  IF OLD.status = 'approved' AND NEW.status = 'locked'
     AND (to_jsonb(NEW) - ARRAY['status', 'locked_by', 'locked_at'])
       IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['status', 'locked_by', 'locked_at']) THEN
    RAISE EXCEPTION 'Locking may only change payroll status and lock metadata';
  END IF;

  IF OLD.status = 'approved' AND NEW.status = 'approved'
     AND to_jsonb(NEW) IS DISTINCT FROM to_jsonb(OLD) THEN
    RAISE EXCEPTION 'Approved payroll runs may only transition to locked';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS payroll_runs_transition_only ON payroll_runs;
CREATE TRIGGER payroll_runs_transition_only
  BEFORE UPDATE OR DELETE ON payroll_runs
  FOR EACH ROW EXECUTE FUNCTION prevent_final_payroll_run_changes();

CREATE OR REPLACE FUNCTION prevent_payroll_run_event_changes()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'Payroll run audit events are append-only';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS payroll_run_events_append_only ON payroll_run_events;
CREATE TRIGGER payroll_run_events_append_only
  BEFORE UPDATE OR DELETE ON payroll_run_events
  FOR EACH ROW EXECUTE FUNCTION prevent_payroll_run_event_changes();
