-- Additive HRMS workflow. Legacy batches must be reviewed before new payroll use.
ALTER TABLE employees ADD COLUMN IF NOT EXISTS last_working_date DATE;
ALTER TABLE leave_requests
 ADD COLUMN IF NOT EXISTS day_fraction NUMERIC(4,3) NOT NULL DEFAULT 1 CHECK(day_fraction > 0 AND day_fraction <= 1),
 ADD COLUMN IF NOT EXISTS coverage_start TIME,
 ADD COLUMN IF NOT EXISTS coverage_end TIME;
ALTER TABLE payroll_attendance_import_batches
 ADD COLUMN IF NOT EXISTS review_state TEXT NOT NULL DEFAULT 'draft' CHECK(review_state IN ('draft','confirmed')),
 ADD COLUMN IF NOT EXISTS review_version INTEGER NOT NULL DEFAULT 1,
 ADD COLUMN IF NOT EXISTS source_hash TEXT,
 ADD COLUMN IF NOT EXISTS context_hash TEXT,
 ADD COLUMN IF NOT EXISTS source_csv TEXT,
 ADD COLUMN IF NOT EXISTS review_issues JSONB NOT NULL DEFAULT '[]',
 ADD COLUMN IF NOT EXISTS confirmed_by INTEGER REFERENCES users(id),
 ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ;
CREATE UNIQUE INDEX IF NOT EXISTS payroll_attendance_source_unique
 ON payroll_attendance_import_batches(source_hash,period_start,period_end) WHERE source_hash IS NOT NULL AND review_state='draft';
ALTER TABLE payroll_daily_attendance
 ADD COLUMN IF NOT EXISTS review_state TEXT NOT NULL DEFAULT 'pending' CHECK(review_state IN ('clear','pending','resolved','excluded')),
 ADD COLUMN IF NOT EXISTS issue_codes JSONB NOT NULL DEFAULT '[]',
 ADD COLUMN IF NOT EXISTS base_hash TEXT,
 ADD COLUMN IF NOT EXISTS review_decision JSONB,
 ADD COLUMN IF NOT EXISTS leave_request_id INTEGER REFERENCES leave_requests(id),
 ADD COLUMN IF NOT EXISTS reviewed_by INTEGER REFERENCES users(id),
 ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;
ALTER TABLE payroll_daily_attendance DROP CONSTRAINT IF EXISTS payroll_daily_attendance_scan_pair_check;
ALTER TABLE payroll_daily_attendance ADD CONSTRAINT payroll_daily_attendance_scan_pair_check CHECK (
 (status IN ('absent','paid_leave','unpaid_leave','partial_leave') AND first_scan_at IS NULL AND last_scan_at IS NULL)
 OR (status='present' AND first_scan_at IS NOT NULL AND last_scan_at IS NOT NULL AND last_scan_at>first_scan_at)
 OR (status='present' AND first_scan_at IS NULL AND last_scan_at IS NULL AND review_state='resolved' AND COALESCE(review_decision->>'action','')='verified_work')
 OR status='exception'
);
CREATE TABLE IF NOT EXISTS payroll_attendance_review_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 batch_id INTEGER NOT NULL REFERENCES payroll_attendance_import_batches(id) ON DELETE RESTRICT,
 employee_id INTEGER REFERENCES employees(id) ON DELETE RESTRICT,
 work_date DATE,
 action TEXT NOT NULL,
 actor_user_id INTEGER REFERENCES users(id),
 reason TEXT NOT NULL,
 previous_value JSONB,
 current_value JSONB,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS attendance_review_events_batch ON payroll_attendance_review_events(batch_id,id);
CREATE TABLE IF NOT EXISTS payroll_payments (
 payroll_run_id INTEGER PRIMARY KEY REFERENCES payroll_runs(id) ON DELETE RESTRICT,
 reference TEXT NOT NULL CHECK(length(trim(reference)) BETWEEN 3 AND 200),
 total_amount NUMERIC(14,2) NOT NULL CHECK(total_amount >= 0),
 paid_on DATE NOT NULL,
 recorded_by INTEGER NOT NULL REFERENCES users(id),
 recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE payroll_attendance_review_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_attendance_import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_daily_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_attendance_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_attendance_import_errors ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_attendance_corrections ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_run_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE payroll_attendance_review_events,payroll_payments FROM anon,authenticated;
REVOKE ALL ON TABLE payroll_attendance_import_batches,payroll_daily_attendance,
 payroll_attendance_events,payroll_attendance_import_errors,payroll_attendance_corrections FROM anon,authenticated;
REVOKE ALL ON TABLE payroll_runs,payroll_run_events FROM anon,authenticated;
CREATE OR REPLACE FUNCTION prevent_hrms_audit_changes() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'HRMS audit and payment records are append-only'; END;
$$;
REVOKE ALL ON FUNCTION prevent_hrms_audit_changes() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER attendance_reviews_append_only BEFORE UPDATE OR DELETE ON payroll_attendance_review_events
 FOR EACH ROW EXECUTE FUNCTION prevent_hrms_audit_changes();
CREATE TRIGGER payroll_payments_append_only BEFORE UPDATE OR DELETE ON payroll_payments
 FOR EACH ROW EXECUTE FUNCTION prevent_hrms_audit_changes();
CREATE OR REPLACE FUNCTION protect_confirmed_attendance() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE batch_state TEXT;
BEGIN
 IF TG_TABLE_NAME='payroll_attendance_import_batches' THEN
   IF OLD.review_state='confirmed' THEN RAISE EXCEPTION 'Confirmed attendance is immutable'; END IF;
 ELSE
   IF TG_OP='INSERT' THEN SELECT review_state INTO batch_state FROM payroll_attendance_import_batches WHERE id=NEW.batch_id;
   ELSE SELECT review_state INTO batch_state FROM payroll_attendance_import_batches WHERE id=OLD.batch_id; END IF;
   IF batch_state='confirmed' THEN RAISE EXCEPTION 'Confirmed attendance is immutable'; END IF;
   IF TG_OP='UPDATE' AND NEW.batch_id<>OLD.batch_id THEN
     SELECT review_state INTO batch_state FROM payroll_attendance_import_batches WHERE id=NEW.batch_id;
     IF batch_state='confirmed' THEN RAISE EXCEPTION 'Confirmed attendance is immutable'; END IF;
   END IF;
 END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION protect_confirmed_attendance() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER attendance_batch_confirmed_only BEFORE UPDATE OR DELETE ON payroll_attendance_import_batches
 FOR EACH ROW EXECUTE FUNCTION protect_confirmed_attendance();
CREATE TRIGGER attendance_days_confirmed_only BEFORE INSERT OR UPDATE OR DELETE ON payroll_daily_attendance
 FOR EACH ROW EXECUTE FUNCTION protect_confirmed_attendance();
