CREATE TABLE announcements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  body TEXT NOT NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal','important')),
  status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  client_key UUID NOT NULL UNIQUE,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  published_at TIMESTAMPTZ,
  archived_at TIMESTAMPTZ,
  CHECK (char_length(trim(title)) > 0),
  CHECK (char_length(trim(body)) BETWEEN 1 AND 10000)
);

CREATE TABLE announcement_recipients (
  announcement_id INTEGER NOT NULL REFERENCES announcements(id) ON DELETE CASCADE,
  employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  employee_name VARCHAR(220) NOT NULL,
  department VARCHAR(100) NOT NULL,
  shift VARCHAR(20) NOT NULL,
  read_at TIMESTAMPTZ,
  PRIMARY KEY (announcement_id,employee_id)
);
CREATE INDEX announcement_recipient_employee_idx ON announcement_recipients(employee_id,announcement_id);
CREATE INDEX announcement_status_date_idx ON announcements(status,created_at DESC,id DESC);
CREATE INDEX announcement_created_by_idx ON announcements(created_by);

-- All access goes through the existing authenticated backend, not the public Data API.
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcement_recipients ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE announcements,announcement_recipients FROM PUBLIC,anon,authenticated;
REVOKE ALL ON SEQUENCE announcements_id_seq FROM PUBLIC,anon,authenticated;
