<script setup>
import { computed, onBeforeUnmount, watch } from 'vue'
import { getTaskAttachmentUrl, getTaskProofUrl } from '@/services/backendService'
import AppButton from '@/components/ui/AppButton.vue'
import { formatPriority, formatStatus, priorityTone, resolveTaskType, statusTone, taskTypeBadgeClass, taskTypeLabel, workIconClass } from './taskPresentation'

const props = defineProps({ show: Boolean, task: { type: Object, default: null }, users: { type: Array, default: () => [] }, canManage: Boolean })
const emit = defineEmits(['close', 'edit', 'complete'])
const isOpen = computed(() => props.show && props.task)
const active = computed(() => ['pending', 'in_progress'].includes(props.task?.status))

function closeOnEscape(event) { if (event.key === 'Escape' && isOpen.value) emit('close') }
watch(isOpen, (show) => { document.body.classList.toggle('overflow-hidden', show); if (show) document.addEventListener('keydown', closeOnEscape); else document.removeEventListener('keydown', closeOnEscape) })
onBeforeUnmount(() => { document.body.classList.remove('overflow-hidden'); document.removeEventListener('keydown', closeOnEscape) })
function dateOnly(value) { return String(value || '').slice(0, 10) }
function formatDate(value) { const iso = dateOnly(value); if (!iso) return '-'; return new Date(`${iso}T00:00:00`).toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' }) }
function userName(id) { const user = props.users.find((item) => Number(item.id) === Number(id)); return user ? `${user.first_name || ''} ${user.last_name || ''}`.trim() || user.email : `User #${id}` }
function assignees() { const ids = Array.isArray(props.task?.assigned_to_ids) && props.task.assigned_to_ids.length ? props.task.assigned_to_ids : [props.task?.assigned_to]; return ids.filter(Boolean).map(userName) }
</script>

<template>
  <Teleport to="body"><div v-if="isOpen" class="fixed inset-0 z-50"><button class="absolute inset-0 bg-black/60 backdrop-blur-[1px]" aria-label="Close details" @click="emit('close')" /><aside class="absolute inset-y-0 right-0 flex w-full max-w-lg flex-col border-l border-gray-800 bg-gray-950 shadow-2xl shadow-black/70" role="dialog" aria-modal="true">
    <header class="border-b border-gray-800 p-5"><div class="flex items-start gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border" :class="workIconClass(task)"><svg v-if="resolveTaskType(task) === 'meeting'" class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></svg><svg v-else class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M9 11l2 2 4-4M5 4h14a1 1 0 011 1v14a1 1 0 01-1 1H5a1 1 0 01-1-1V5a1 1 0 011-1z"/></svg></span><div class="min-w-0 flex-1"><h2 class="text-xl font-semibold leading-7 text-gray-100">{{ task.title }}</h2><div class="mt-2 flex flex-wrap gap-2"><span class="rounded-full border px-2 py-0.5 text-xs font-semibold" :class="taskTypeBadgeClass(resolveTaskType(task))">{{ taskTypeLabel(resolveTaskType(task)) }}</span><span class="rounded-full px-2 py-0.5 text-xs font-semibold" :class="statusTone(task.status)">{{ formatStatus(task.status) }}</span><span class="rounded-full px-2 py-0.5 text-xs font-semibold" :class="priorityTone(task.priority)">{{ formatPriority(task.priority) }}</span></div></div><button class="icon-button h-9 w-9 text-xl" @click="emit('close')">×</button></div></header>
    <div class="min-h-0 flex-1 overflow-y-auto"><section class="border-b border-gray-800 p-5"><h3 class="text-xs font-semibold uppercase tracking-wider text-gray-500">Description</h3><p class="mt-3 whitespace-pre-wrap text-sm leading-6 text-gray-300">{{ task.description || 'No description provided.' }}</p></section><section class="border-b border-gray-800 p-5"><h3 class="text-sm font-semibold text-gray-200">Schedule & context</h3><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-gray-500">Due date</dt><dd class="text-right text-gray-200">{{ formatDate(task.due_date) }}</dd></div><div class="flex justify-between gap-4"><dt class="text-gray-500">Client</dt><dd class="text-right text-gray-200">{{ task.company_name || 'Internal' }}</dd></div><div class="flex justify-between gap-4"><dt class="text-gray-500">Service</dt><dd class="text-right text-gray-200">{{ task.service_type?.replaceAll('_', ' ') || 'General' }}</dd></div></dl></section><section class="border-b border-gray-800 p-5"><h3 class="text-sm font-semibold text-gray-200">Assignees</h3><div class="mt-3 flex flex-wrap gap-2"><span v-for="name in assignees()" :key="name" class="rounded-full border border-gray-700 bg-gray-900 px-3 py-1.5 text-xs text-gray-300">{{ name }}</span><span v-if="!assignees().length" class="text-sm text-gray-500">No employees assigned.</span></div></section><section v-if="task.attachment_data || task.proof_of_work_data" class="p-5"><h3 class="text-sm font-semibold text-gray-200">Files</h3><div class="mt-3 space-y-2"><a v-if="task.attachment_data" :href="getTaskAttachmentUrl(task.id)" target="_blank" rel="noopener" class="flex items-center justify-between rounded-xl border border-gray-800 bg-gray-900 p-3 text-sm text-gray-200 hover:border-primary-700"><span>{{ task.attachment_name || 'Task attachment' }}</span><span class="text-primary-300">View ↗</span></a><a v-if="task.proof_of_work_data" :href="getTaskProofUrl(task.id)" target="_blank" rel="noopener" class="flex items-center justify-between rounded-xl border border-gray-800 bg-gray-900 p-3 text-sm text-gray-200 hover:border-primary-700"><span>{{ task.proof_of_work_name || 'Proof of work' }}</span><span class="text-primary-300">View ↗</span></a></div></section></div>
    <footer class="flex justify-end gap-2 border-t border-gray-800 bg-gray-950 p-4"><AppButton v-if="canManage" variant="secondary" @click="emit('edit', task)">Edit</AppButton><AppButton v-if="active" @click="emit('complete', task)">Mark complete</AppButton><AppButton v-else variant="secondary" @click="emit('close')">Close</AppButton></footer>
  </aside></div></Teleport>
</template>
