const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path')
const {createAnnouncementService}=require('./services/announcementService')
const {createAnnouncementEmailSender}=require('./services/announcementEmailService')

// Private fixture schema in one rolled-back transaction; no real announcements or notifications.
test('announcement workflow: audience, private drafts, idempotent publishing, recipient access and retained archive',
 {skip:process.env.RUN_ANNOUNCEMENT_DATABASE_TEST!=='true'},async()=>{
 require('dotenv').config({path:path.resolve(__dirname,'../.env'),quiet:true})
 const {Pool}=require('pg'),pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.PGSSLMODE==='disable'?false:{rejectUnauthorized:false}})
 const client=await pool.connect(),schema=`announcements_test_${Date.now()}`
 try{
  await client.query('BEGIN')
  await client.query(`CREATE SCHEMA ${schema}; SET LOCAL search_path TO ${schema},public`)
  await client.query(`CREATE TABLE employees(id INTEGER PRIMARY KEY,employee_code TEXT,first_name TEXT,last_name TEXT,department TEXT,shift TEXT,status TEXT);
   CREATE TABLE users(id INTEGER PRIMARY KEY,email TEXT,role TEXT,employee_id INTEGER REFERENCES employees(id));
   CREATE TABLE notifications(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER,type TEXT,title TEXT,message TEXT,target_table TEXT,target_id INTEGER);
   CREATE TABLE audit_logs(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER,action TEXT,target_table TEXT,target_id INTEGER);
   INSERT INTO employees VALUES(1,'001','Ana','Fixture','HR','day','active'),(2,'002','Ben','Fixture','Sales','night','active'),
    (3,'003','Cara','Fixture','HR','night','on_leave'),(4,'004','Dan','Fixture','Sales','day','terminated'),(5,'005','Eve','Fixture','Sales','day','active');
   INSERT INTO users VALUES(1,'hr@example.test','hr',NULL),(2,'ana@example.test','employee',1),(3,'ben@example.test','employee',2),(4,'ceo@example.test','ceo',NULL);`)
  await client.query(fs.readFileSync(path.resolve(__dirname,'../migrations/026_announcements.sql'),'utf8'))
  await client.query(fs.readFileSync(path.resolve(__dirname,'../migrations/027_announcement_ceo_notification.sql'),'utf8'))
  let serial=0,inOperation=false
  const db={query:(sql,params)=>client.query(sql,params),transaction:async(fn)=>{
   const sp=`operation_${++serial}`;await client.query(`SAVEPOINT ${sp}`)
   try{inOperation=true;const result=await fn(db);await client.query(`RELEASE SAVEPOINT ${sp}`);return result}
   catch(error){await client.query(`ROLLBACK TO SAVEPOINT ${sp}`);throw error}
   finally{inOperation=false}
  }}
  const copies=[],emails=[]
  const sendEmails=createAnnouncementEmailSender({db,sendEmailNotification:async message=>emails.push(message),frontendOrigin:'https://hr.example.test'})
  const service=createAnnouncementService({db,sendAnnouncementEmails:async item=>{assert.equal(inOperation,false);copies.push(item);await sendEmails(item)}}),hr={id:1,role:'hr'},ana={id:2,role:'employee',employee_id:1},ben={id:3,role:'employee',employee_id:2}
  const audience=await service.audience()
  assert.deepEqual(audience.map(p=>p.id),[1,2,3,5]);assert.equal(audience.find(p=>p.id===3).has_account,false)
  const input={title:'Fixture announcement',body:'Fixture message\nSecond line',priority:'important',recipientIds:[1,3],clientKey:crypto.randomUUID()}
  let draft=await service.save(input,hr)
  assert.equal(draft.status,'draft');assert.equal(draft.recipients.length,2);assert.equal(draft.notify_ceo,false)
  assert.equal((await service.list({status:'all'},ana)).total,0)
  await assert.rejects(service.get(draft.id,ana),error=>error.status===404)
  assert.equal((await service.save(input,hr)).id,draft.id)
  assert.equal((await client.query('SELECT COUNT(*)::integer AS n FROM announcements')).rows[0].n,1)
  await assert.rejects(service.save({...input,recipientIds:[4]},hr),error=>error.status===409)
  await assert.rejects(service.save({...input,clientKey:crypto.randomUUID(),recipientIds:[4]},hr),error=>error.status===409)
  assert.equal((await client.query('SELECT COUNT(*)::integer AS n FROM announcements')).rows[0].n,1)
  await assert.rejects(service.save({...input,title:'Must roll back',version:draft.version,recipientIds:[4]},hr,draft.id),error=>error.status===409)
  assert.equal((await service.get(draft.id,hr)).title,input.title)
  assert.equal((await service.get(draft.id,hr)).version,draft.version)
  assert.equal((await client.query('SELECT COUNT(*)::integer AS n FROM notifications')).rows[0].n,0)
  assert.equal(emails.length,0)
  await assert.rejects(service.save({...input,version:0},hr,draft.id),error=>error.status===409)
  draft=await service.save({...input,version:draft.version,recipientIds:[1,2]},hr,draft.id)
  // Combined filters must refer to a single employee: HR day + Sales night does not match HR night.
  assert.equal((await service.list({status:'draft',shift:'night',department:'HR'},hr)).total,0)
  assert.equal((await service.list({status:'draft',shift:'day',department:'HR'},hr)).total,1)
  await assert.rejects(service.publish(draft.id,draft.version-1,hr),error=>error.status===409)
  let published=await service.publish(draft.id,draft.version,hr)
  assert.equal(published.status,'published')
  assert.equal((await client.query('SELECT COUNT(*)::integer AS n FROM notifications')).rows[0].n,2)
  await service.publish(draft.id,draft.version,hr)
  assert.equal((await client.query('SELECT COUNT(*)::integer AS n FROM notifications')).rows[0].n,2)
  assert.equal(copies.length,1)
  assert.deepEqual(emails.map(m=>m.to),['ana@example.test','ben@example.test'])
  assert.equal((await client.query('SELECT COUNT(*)::integer AS n FROM notifications WHERE user_id=4')).rows[0].n,0)
  const employeeItem=await service.get(draft.id,ana)
  assert.equal(employeeItem.body,input.body);assert.equal(employeeItem.recipients,undefined);assert.equal(employeeItem.client_key,undefined)
  assert.equal((await service.list({status:'published'},ana)).total,1)
  const firstRead=await service.markRead(draft.id,ana),secondRead=await service.markRead(draft.id,ana)
  assert.equal(firstRead.read_at.toISOString(),secondRead.read_at.toISOString())
  assert.equal((await service.list({status:'published'},hr)).items[0].read_count,1)
  await assert.rejects(service.get(draft.id,{id:9,role:'employee',employee_id:5}),error=>error.status===404)
  await assert.rejects(service.markRead(draft.id,{id:9,role:'employee',employee_id:5}),error=>error.status===404)
  await assert.rejects(service.save({...input,version:published.version},hr,draft.id),error=>error.status===409)
  const archived=await service.archive(draft.id,published.version,hr)
  assert.equal(archived.status,'archived');assert.equal(archived.body,input.body)
  assert.equal((await service.list({status:'published'},ana)).total,0)
  assert.equal((await service.list({status:'archived'},ben)).total,1)
  // A CEO copy is opt-in, retained in drafts and scheduled only after publishing commits.
  await client.query("INSERT INTO users VALUES(5,'selected-ceo@example.test','ceo',1)")
  const copyInput={...input,title:'CEO copy fixture',clientKey:crypto.randomUUID(),recipientIds:[1],notifyCeo:true}
  let copyDraft=await service.save(copyInput,hr)
  assert.equal(copyDraft.notify_ceo,true);assert.equal(copies.length,1);assert.equal(emails.length,2)
  assert.equal((await service.save(copyInput,hr)).id,copyDraft.id)
  await assert.rejects(service.save({...copyInput,notifyCeo:false},hr),error=>error.status===409)
  copyDraft=await service.save({...copyInput,notifyCeo:false,version:copyDraft.version},hr,copyDraft.id)
  assert.equal(copyDraft.notify_ceo,false)
  copyDraft=await service.save({...copyInput,version:copyDraft.version},hr,copyDraft.id)
  assert.equal(copyDraft.notify_ceo,true);assert.equal(copies.length,1);assert.equal(emails.length,2)
  await service.publish(copyDraft.id,copyDraft.version,hr)
  assert.equal(copies.length,2);assert.equal(copies[1].id,copyDraft.id);assert.equal(copies[1].body,input.body)
  assert.deepEqual(emails.slice(2).map(m=>m.to),['ana@example.test','ceo@example.test','selected-ceo@example.test'])
  const copyNotices=(await client.query('SELECT user_id FROM notifications WHERE target_id=$1 ORDER BY user_id',[copyDraft.id])).rows
  assert.deepEqual(copyNotices.map(n=>n.user_id),[2,4,5]) // selected CEO receives only one notice
  await service.publish(copyDraft.id,copyDraft.version,hr)
  assert.equal(copies.length,2);assert.equal(emails.length,5)
  assert.equal((await client.query('SELECT COUNT(*)::integer AS n FROM notifications WHERE target_id=$1',[copyDraft.id])).rows[0].n,3)
  // A draft for a no-login employee still stays private and checks active status again at publish.
  const other=await service.save({...input,clientKey:crypto.randomUUID(),recipientIds:[3],notifyCeo:true},hr)
  await client.query("UPDATE employees SET status='terminated' WHERE id=3")
  await assert.rejects(service.publish(other.id,other.version,hr),error=>error.status===409)
  assert.equal((await service.get(other.id,hr)).status,'draft')
  assert.equal(copies.length,2);assert.equal(emails.length,5)
  const security=(await client.query(`SELECT c.relname,c.relrowsecurity,
   has_table_privilege('anon',c.oid,'SELECT') AS anon_read,has_table_privilege('authenticated',c.oid,'SELECT') AS auth_read
   FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=$1 AND c.relname IN ('announcements','announcement_recipients')`,[schema])).rows
  assert.equal(security.length,2);assert.ok(security.every(t=>t.relrowsecurity && !t.anon_read && !t.auth_read))
 }finally{await client.query('ROLLBACK');client.release();await pool.end()}
})
