const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs'),path=require('node:path')
const {createAttendanceReviewService,loadContext,fingerprint}=require('./services/attendanceReviewService')
const {createPayrollService}=require('./services/payrollService')

// Explicit opt-in: isolated schema and all fixtures are rolled back, never public employee data.
test('HRMS database workflow: preview, official leave, immutable confirmation, recalculation and payment release',
 {skip:process.env.RUN_HRMS_DATABASE_TEST!=='true'},async()=>{
 require('dotenv').config({path:path.resolve(__dirname,'../.env'),quiet:true})
 const {Pool}=require('pg')
 const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.PGSSLMODE==='disable'?false:{rejectUnauthorized:false}})
 const client=await pool.connect(),schema=`hrms_test_${Date.now()}`
 const previousFinalization=process.env.PAYROLL_FINALIZATION_ENABLED
 const previousDayScope=process.env.PAYROLL_DAY_SHIFT_ONLY
 const previousNodeEnv=process.env.NODE_ENV
 process.env.PAYROLL_FINALIZATION_ENABLED='true'
 process.env.PAYROLL_DAY_SHIFT_ONLY='false'
 try {
  await client.query('BEGIN ISOLATION LEVEL SERIALIZABLE')
  await client.query(`CREATE SCHEMA ${schema}`)
  await client.query(`SET LOCAL search_path TO ${schema},public`)
  await client.query(`CREATE TABLE users(id INTEGER PRIMARY KEY,role TEXT,email TEXT,employee_id INTEGER);
   CREATE TABLE employees(id INTEGER PRIMARY KEY,employee_code TEXT,first_name TEXT,last_name TEXT,status TEXT,shift TEXT,department TEXT,date_hired DATE,leave_credits NUMERIC,leave_credits_reset_year INTEGER,updated_at TIMESTAMPTZ);
   CREATE TABLE leave_requests(id INTEGER PRIMARY KEY,employee_id INTEGER,start_date DATE,end_date DATE,status TEXT,leave_type_name TEXT,leave_pay_type TEXT,leave_days NUMERIC,paid_days NUMERIC,unpaid_days NUMERIC,credits_deducted NUMERIC);
   CREATE TABLE philippine_holidays(holiday_date DATE PRIMARY KEY,is_working_day BOOLEAN,holiday_type TEXT,name TEXT);
   CREATE TABLE audit_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER,action TEXT,target_table TEXT,target_id INTEGER);
   INSERT INTO users VALUES(1,'hr','fixture@example.test',1);
   INSERT INTO employees VALUES(1,'EMP-1','Fixture','One','active','day','Test','2026-01-01',10,2026,NOW()),(2,'EMP-2','Fixture','Two','active','day','Test','2026-01-01',10,2026,NOW());`)
  for(const filename of ['020_payroll_foundation.sql','021_payroll_biometric_identity_and_lateness.sql','022_payroll_cola_and_charges.sql','024_attendance_review_and_hrms_workflow.sql','025_payroll_overnight_shifts.sql','028_payroll_shift_workspaces.sql','029_payroll_practice_runs.sql'])await client.query(fs.readFileSync(path.resolve(__dirname,'../migrations',filename),'utf8'))
  await client.query(`INSERT INTO payroll_employee_profiles(employee_id,effective_from,monthly_basic_salary) VALUES(1,'2026-01-01',15000),(2,'2026-01-01',15000);
   INSERT INTO payroll_biometric_identities(employee_id,person_id) VALUES(1,'00041'),(2,'00042')`)
  const tx={query:async(sql,params)=>/^SET TRANSACTION/.test(sql)?{rows:[]}:client.query(sql,params)}
  const db={query:tx.query,transaction:fn=>fn(tx)}
  const review=createAttendanceReviewService({db}),payroll=createPayrollService({db}),actor={id:1,role:'hr',name:'Fixture HR'}
  assert.equal((await payroll.profileHistory(1)).length,1)
  const input={fileName:'fixture.csv',periodStart:'2026-09-11',periodEnd:'2026-09-25'}
  const records=[]
  for(let date=new Date('2026-09-11T00:00:00Z');date<=new Date('2026-09-25T00:00:00Z');date.setUTCDate(date.getUTCDate()+1)){
   if([0,6].includes(date.getUTCDay()))continue
   const key=date.toISOString().slice(0,10)
   records.push(`00041,${key} ${key==='2026-09-11'?'09:10':'09:00'},Main_Door_Out_Door1_Entrance Card Reader1`,
    `00041,${key} 18:00,Main_Door_IN_Door1_Entrance Card Reader1`)
  }
  input.csvText='Person ID,Time,Attendance Check Point\n'+records.join('\n')
  const p=await review.preview(input)
  assert.equal((await client.query('SELECT COUNT(*)::integer AS n FROM payroll_attendance_import_batches')).rows[0].n,0)
  assert.equal(p.summary.employeeDays,22);assert.equal(p.summary.missingRecords,11)
  let batch=await review.save({...input,previewToken:p.preview_token},actor)
  assert.equal((await review.save({...input,previewToken:p.preview_token},actor)).id,batch.id)
  await assert.rejects(review.confirm(batch.id,batch.review_version,'',actor),/resolve every/)
  await assert.rejects(payroll.previewRun({...input,payday:'2026-09-30',cutoff:'second',attendanceBatchId:batch.id}),/confirm attendance/)
  const first=batch.daily.find(d=>d.employee_id===1&&d.work_date==='2026-09-11'),oldVersion=batch.review_version
  batch=await review.resolve(batch.id,batch.review_version,first.employee_id,first.work_date,{action:'acknowledge',reason:'Verified lateness'},actor)
  await assert.rejects(review.refresh(batch.id,oldVersion,actor),/Another HR action/)
  await client.query(`INSERT INTO leave_requests VALUES(8,2,'2026-09-16','2026-09-16','approved','Vacation Leave','paid',1,1,0,1,1,NULL,NULL);UPDATE employees SET leave_credits=9 WHERE id=2`)
  batch=await review.refresh(batch.id,batch.review_version,actor)
  batch=await review.revokeLeave(batch.id,batch.review_version,8,'Corrected wrong paper-leave date',actor)
  assert.equal((await client.query('SELECT status FROM leave_requests WHERE id=8')).rows[0].status,'cancelled')
  assert.equal(Number((await client.query('SELECT leave_credits FROM employees WHERE id=2')).rows[0].leave_credits),10)
  await assert.rejects(review.revokeLeave(batch.id,batch.review_version,8,'Prevent duplicate refund',actor),/approved leave/)
  // Simulates an official approved leave supplied by the existing transactional HR recorder.
  await client.query(`INSERT INTO leave_requests VALUES(7,2,'2026-09-21','2026-09-22','approved','Vacation Leave','partial_paid',2,1,1,1,1,NULL,NULL)`)
  await assert.rejects(review.confirm(batch.id,batch.review_version,'',actor),/Refresh the review/)
  batch=await review.refresh(batch.id,batch.review_version,actor)
  assert.equal(batch.daily.find(d=>d.employee_id===1&&d.work_date==='2026-09-11').review_state,'resolved')
  for(const d of batch.daily.filter(d=>d.review_state==='pending')){
   if(d.leave_request_id&&d.work_date==='2026-09-22')await assert.rejects(review.resolve(batch.id,batch.review_version,d.employee_id,d.work_date,{action:'link_leave',leaveId:7,paidFraction:1,reason:'Invalid double allocation'},actor),/exceeds the official leave totals/)
   const decision=d.leave_request_id?{action:'link_leave',leaveId:7,paidFraction:d.work_date==='2026-09-21'?1:0,reason:'Verified paper leave allocation'}:{action:'verified_work',reason:'Device issue; supervisor verified work'}
   batch=await review.resolve(batch.id,batch.review_version,d.employee_id,d.work_date,decision,actor)
  }
  batch=await review.confirm(batch.id,batch.review_version,'',actor)
  assert.equal(batch.review_state,'confirmed')
  assert.equal((await review.confirm(batch.id,1,'',actor)).review_version,batch.review_version)
  assert.equal(batch.daily.find(d=>d.employee_id===2&&d.work_date==='2026-09-12'),undefined)
  assert.ok(batch.daily.some(d=>d.status==='present'&&!d.first_scan_at&&d.review_decision.action==='verified_work'))
  async function rejectedSql(sql,values,pattern){await client.query('SAVEPOINT rejected');try{await assert.rejects(client.query(sql,values),pattern)}finally{await client.query('ROLLBACK TO SAVEPOINT rejected');await client.query('RELEASE SAVEPOINT rejected')}}
  await rejectedSql('UPDATE payroll_daily_attendance SET late_minutes=0 WHERE batch_id=$1',[batch.id],/Confirmed attendance is immutable/)
  await rejectedSql('DELETE FROM payroll_attendance_review_events WHERE batch_id=$1',[batch.id],/append-only/)
  const runInput={...input,payday:'2026-09-30',cutoff:'second',includeContributions:false,attendanceBatchId:batch.id}
  let run=await payroll.previewRun(runInput,actor),line=run.lines.find(l=>l.employee_id===1)
  await payroll.updateManualEarnings(run.id,line.id,[{type:'night_differential',amount:100,note:'HR-approved manual calculation'}],actor)
  line=await payroll.updateCharges(run.id,line.id,[{type:'basic_pay_adjustment',amount:300,note:'Verified sample adjustment'},{type:'tax_withholding',amount:50,note:'HR-approved withholding'}],actor)
  // Workbook 13th-month basis: basic - absences + basic adjustment; tardiness/undertime is not subtracted.
  const earned=Number(line.gross_salary)-Number(line.absence_deduction)+300
  assert.equal(Number(line.thirteenth_month_accrual),Math.round(earned/12*100)/100)
  run=await payroll.previewRun(runInput,actor)
  line=run.lines.find(l=>l.employee_id===1)
  assert.equal(line.details.manualEarnings[0].amount,100);assert.equal(line.details.charges.length,2)
  run=await payroll.approveRun(run.id,actor) // Same HR may prepare and approve, per company authorization.
  await assert.rejects(payroll.lockRun(run.id,actor),/Record actual payment/)
  assert.equal((await payroll.listMyLines({employeeId:1})).length,0)
  const amount=run.lines.reduce((sum,l)=>sum+Number(l.net_pay),0),payment={reference:'FIXTURE-ONLY',paidOn:'2026-09-30',expectedTotal:amount}
  await assert.rejects(payroll.recordPayment(run.id,{...payment,expectedTotal:amount+1},actor),/Verify the approved net total/)
  run=await payroll.recordPayment(run.id,payment,actor)
  assert.equal((await payroll.recordPayment(run.id,payment,actor)).payment.reference,'FIXTURE-ONLY')
  assert.equal((await payroll.listMyLines({employeeId:1})).length,0)
  run=await payroll.lockRun(run.id,actor);assert.equal(run.status,'locked')
  assert.equal((await payroll.listMyLines({employeeId:1})).length,1)
  await assert.rejects(payroll.upsertProfile({employeeId:1,effectiveFrom:'2026-09-11',monthlyBasicSalary:16000},actor),/overlaps finalized payroll/)
  await rejectedSql('DELETE FROM payroll_payments WHERE payroll_run_id=$1',[run.id],/append-only/)
  const protectedTables=(await client.query(`SELECT c.relname,c.relrowsecurity,has_table_privilege('anon',c.oid,'SELECT') AS anon_read,has_table_privilege('authenticated',c.oid,'SELECT') AS auth_read FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=$1 AND c.relname IN ('payroll_attendance_import_batches','payroll_daily_attendance','payroll_attendance_review_events','payroll_payments','payroll_runs','payroll_run_events')`,[schema])).rows
  assert.equal(protectedTables.length,6);assert.ok(protectedTables.every(t=>t.relrowsecurity&&!t.anon_read&&!t.auth_read))
  assert.equal(fingerprint(await loadContext(db,input.periodStart,input.periodEnd)),batch.context_hash)
  // Night fixtures remain in this isolated transaction, never public salaries.
  await client.query("UPDATE employees SET shift='night' WHERE id=1; UPDATE employees SET last_working_date='2026-09-25' WHERE id=2")
  const nightProfile=await payroll.upsertProfile({employeeId:1,effectiveFrom:'2026-10-01',monthlyBasicSalary:15000,workStartTime:'21:00',workEndTime:'06:00'},actor)
  assert.equal(nightProfile.work_start_time,'21:00:00');assert.equal(nightProfile.work_end_time,'06:00:00')
  await assert.rejects(payroll.upsertProfile({employeeId:1,effectiveFrom:'2026-10-02',monthlyBasicSalary:15000,workStartTime:'21:00',workEndTime:'05:00'},actor),/eight paid hours/)
  const nightRecords=[]
  for(let date=new Date('2026-10-11T00:00:00Z');date<=new Date('2026-10-25T00:00:00Z');date.setUTCDate(date.getUTCDate()+1)){
   if([0,6].includes(date.getUTCDay()))continue
   const key=date.toISOString().slice(0,10),next=new Date(date.getTime()+86400000).toISOString().slice(0,10)
   nightRecords.push(`00041,${key} 21:00,Main_Door_Out_Door1_Entrance Card Reader1`,`00041,${next} 06:00,Main_Door_IN_Door1_Entrance Card Reader1`)
  }
  const nightInput={fileName:'night-fixture.csv',periodStart:'2026-10-11',periodEnd:'2026-10-25',csvText:'Person ID,Time,Attendance Check Point\n'+nightRecords.join('\n')}
  const nightPreview=await review.preview(nightInput)
  assert.equal(nightPreview.daily.length,10);assert.ok(nightPreview.daily.every(d=>d.status==='present'&&d.review_state==='clear'&&d.overnight))
  let nightBatch=await review.save({...nightInput,previewToken:nightPreview.preview_token},actor)
  nightBatch=await review.confirm(nightBatch.id,nightBatch.review_version,'Verified weekend cutoff export',actor)
  const nightRunInput={...nightInput,payday:'2026-10-30',cutoff:'second',includeContributions:true,attendanceBatchId:nightBatch.id}
  let nightRun=await payroll.previewRun(nightRunInput,actor),nightLine=nightRun.lines[0]
  assert.equal(nightLine.details.nightDifferential.paidMinutes,4200)
  assert.equal(nightLine.details.nightDifferential.amount,603.45);assert.equal(Number(nightLine.net_pay),6753.45)
  assert.equal(nightLine.details.nightDifferential.reviewRequired,false)
  const {payrollBreakdown}=require('./services/payrollPayslipService')
  assert.equal(payrollBreakdown(nightLine).totalEarnings,8103.45)
  nightLine=await payroll.updateManualEarnings(nightRun.id,nightLine.id,[{type:'night_differential',amount:700,note:'Verified total night earnings override'}],actor)
  assert.equal(Number(nightLine.net_pay),6850)
  await assert.rejects(payroll.updateManualEarnings(nightRun.id,nightLine.id,[{type:'night_differential',amount:700,note:'First duplicate'},{type:'night_differential',amount:100,note:'Second duplicate'}],actor),/one total night/)
  nightRun=await payroll.previewRun(nightRunInput,actor);nightLine=nightRun.lines[0]
  assert.equal(Number(nightLine.net_pay),6850);assert.equal(nightLine.details.automaticEarnings.length,1);assert.equal(nightLine.details.manualEarnings.length,1)
  nightLine=await payroll.updateManualEarnings(nightRun.id,nightLine.id,[],actor)
  assert.equal(Number(nightLine.net_pay),6753.45)
  assert.equal(nightLine.details.sssAssessment.nightDifferentialPay,603.45)
  assert.equal(Number(nightLine.employee_sss),775)
  await payroll.overrideFirstCutoffPay(nightRun.id,nightLine.id,7500,'Verified first cutoff paid compensation',actor)
  await payroll.approveRun(nightRun.id,actor)
  process.env.PAYROLL_DAY_SHIFT_ONLY='true'
  assert.ok((await payroll.listProfiles()).every(p=>p.shift!=='night'))
  assert.equal((await review.preview(nightInput)).daily.length,0)
  assert.equal((await review.list()).find(b=>b.id===nightBatch.id).scope_needs_refresh,true)
  await assert.rejects(payroll.previewRun(nightRunInput,actor),/selected shift|changed after attendance confirmation/)
  const dayRecords=[]
  for(let date=new Date('2026-08-26T00:00:00Z');date<=new Date('2026-09-10T00:00:00Z');date.setUTCDate(date.getUTCDate()+1)){
   if([0,6].includes(date.getUTCDay()))continue
   const key=date.toISOString().slice(0,10)
   dayRecords.push(`00042,${key} 09:00,Main_Door_Out_Door1_Entrance Card Reader1`,`00042,${key} 18:00,Main_Door_IN_Door1_Entrance Card Reader1`)
  }
  const dayInput={fileName:'day-only-fixture.csv',periodStart:'2026-08-26',periodEnd:'2026-09-10',csvText:'Person ID,Time,Attendance Check Point\n'+dayRecords.join('\n')}
  const dayPreview=await review.preview(dayInput)
  assert.equal(dayPreview.summary.flaggedDays,0);assert.ok(dayPreview.daily.every(d=>d.employee_id===2))
  let dayBatch=await review.save({...dayInput,previewToken:dayPreview.preview_token},actor)
  dayBatch=await review.confirm(dayBatch.id,dayBatch.review_version,'',actor)
  const dayHistory=(await review.list()).find(b=>b.id===dayBatch.id)
  assert.equal(dayHistory.payroll_scope,'day');assert.equal(dayHistory.scope_needs_refresh,false)
  const dayRun=await payroll.previewRun({...dayInput,payday:'2026-09-15',cutoff:'first',includeContributions:false,attendanceBatchId:dayBatch.id},actor)
  assert.equal(dayRun.lines.length,1);assert.equal(dayRun.lines[0].employee_id,2)
  assert.equal(Number(dayRun.lines[0].net_pay),7500);assert.equal(dayRun.rule_snapshot.payrollScope,'day')
  // Separate exports/runs must coexist for the same payday, including identical source files.
  await client.query('UPDATE employees SET last_working_date=NULL WHERE id=2')
  const splitRows=[]
  for(let date=new Date('2026-12-11T00:00:00Z');date<=new Date('2026-12-25T00:00:00Z');date.setUTCDate(date.getUTCDate()+1)){
   if([0,6].includes(date.getUTCDay()))continue
   const key=date.toISOString().slice(0,10),next=new Date(date.getTime()+86400000).toISOString().slice(0,10)
   splitRows.push(`00042,${key} 09:00,Main_Door_Out_Door1_Entrance Card Reader1`,`00042,${key} 18:00,Main_Door_IN_Door1_Entrance Card Reader1`,
    `00041,${key} 21:00,Main_Door_Out_Door1_Entrance Card Reader1`,`00041,${next} 06:00,Main_Door_IN_Door1_Entrance Card Reader1`)
  }
  const splitInput={fileName:'split-fixture.csv',periodStart:'2026-12-11',periodEnd:'2026-12-25',csvText:'Person ID,Time,Attendance Check Point\n'+splitRows.join('\n')}
  const shiftBatches={}
  for(const shift of ['day','night']){
   const input={...splitInput,payrollScope:shift},p=await review.preview(input)
   assert.equal(p.summary.flaggedDays,0);assert.equal(p.summary.employees,1)
   let b=await review.save({...input,previewToken:p.preview_token},actor)
   assert.equal((await review.save({...input,previewToken:p.preview_token},actor)).id,b.id)
   b=await review.refresh(b.id,b.review_version,actor)
   assert.equal(b.payrollScope,shift)
   b=await review.confirm(b.id,b.review_version,'',actor)
   shiftBatches[shift]=b
  }
  assert.notEqual(shiftBatches.day.id,shiftBatches.night.id)
  await assert.rejects(payroll.previewRun({...splitInput,shift:'night',payday:'2026-12-30',cutoff:'second',attendanceBatchId:shiftBatches.day.id},actor),/selected shift/)
  const splitRuns={}
  for(const shift of ['day','night']){
   splitRuns[shift]=await payroll.previewRun({...splitInput,shift,payday:'2026-12-30',cutoff:'second',attendanceBatchId:shiftBatches[shift].id},actor)
   assert.equal(splitRuns[shift].rule_snapshot.payrollScope,shift)
   assert.equal(splitRuns[shift].lines.length,1)
   assert.equal(splitRuns[shift].lines[0].employee_id,shift==='day'?2:1)
  }
  assert.notEqual(splitRuns.day.id,splitRuns.night.id)
  await payroll.updateManualEarnings(splitRuns.night.id,splitRuns.night.lines[0].id,[{type:'overtime',amount:123,note:'Verified fixture overtime'}],actor)
  const recalculated=await payroll.previewRun({...splitInput,shift:'day',payday:'2026-12-30',cutoff:'second',attendanceBatchId:shiftBatches.day.id},actor)
  assert.equal(recalculated.id,splitRuns.day.id)
  assert.equal((await payroll.getRun(splitRuns.night.id)).lines[0].details.manualEarnings[0].amount,123)
  assert.ok((await review.list('night')).filter(b=>b.payroll_scope==='night').every(b=>!b.scope_needs_refresh))
  // A practice cohort can complete the workflow independently of the real cutoff,
  // using a current salary hypothetically, without changing its effective history or publishing payslips.
  process.env.NODE_ENV='test';process.env.PAYROLL_FINALIZATION_ENABLED='false'
  await client.query(`INSERT INTO payroll_employee_profiles(employee_id,effective_from,monthly_basic_salary) VALUES(2,'2027-01-01',17500)`)
  const practiceInput={...splitInput,payrollScope:'day',isTest:true,employeeIds:[2]}
  const practicePreview=await review.preview(practiceInput)
  assert.equal(practicePreview.isTest,true);assert.equal(practicePreview.summary.employees,1)
  assert.equal(practicePreview.summary.flaggedDays,0);assert.equal(Number(practicePreview.daily[0].profile.monthly_basic_salary),17500)
  assert.equal(practicePreview.daily[0].profile.source_effective_from,'2027-01-01')
  await assert.rejects(review.preview({...practiceInput,employeeIds:[999]}),/Selected employees/)
  await assert.rejects(review.preview({...practiceInput,isTest:false}),/subsets/)
  let practiceBatch=await review.save({...practiceInput,previewToken:practicePreview.preview_token},actor)
  practiceBatch=await review.refresh(practiceBatch.id,practiceBatch.review_version,actor)
  assert.deepEqual(practiceBatch.employeeIds,[2]);assert.equal(practiceBatch.isTest,true)
  await assert.rejects(review.revokeLeave(practiceBatch.id,practiceBatch.review_version,7,'Test must not touch real leave',actor),/cannot change official leave/)
  practiceBatch=await review.confirm(practiceBatch.id,practiceBatch.review_version,'',actor)
  assert.equal((await review.list('day')).find(b=>b.id===practiceBatch.id).is_test,true)
  const practiceRunInput={...splitInput,shift:'day',payday:'2026-12-30',cutoff:'second',attendanceBatchId:practiceBatch.id}
  let practiceRun=await payroll.previewRun(practiceRunInput,actor)
  assert.notEqual(practiceRun.id,splitRuns.day.id);assert.equal(practiceRun.lines.length,1)
  assert.equal(practiceRun.rule_snapshot.isTest,true);assert.equal(Number(practiceRun.lines[0].gross_salary),8750)
  await assert.rejects(payroll.approveRun(splitRuns.day.id,actor),{statusCode:403})
  practiceRun=await payroll.approveRun(practiceRun.id,actor)
  assert.equal(practiceRun.status,'approved')
  practiceRun=await payroll.recordPayment(practiceRun.id,{reference:'Simulated fixture',paidOn:'2026-01-01',expectedTotal:8750},actor)
  assert.equal(practiceRun.payment.reference,'TEST ONLY - Simulated fixture')
  practiceRun=await payroll.lockRun(practiceRun.id,actor)
  assert.equal(practiceRun.status,'locked')
  assert.equal(await payroll.listMyLines({runId:practiceRun.id,employeeId:2}),null)
  assert.equal((await payroll.getRun(splitRuns.day.id)).status,'draft')
  assert.equal((await payroll.profileHistory(2)).find(p=>Number(p.monthly_basic_salary)===17500).effective_from,'2027-01-01')
  process.env.NODE_ENV='production'
  await assert.rejects(review.preview(practiceInput),{statusCode:403})
 }finally{
  await client.query('ROLLBACK');client.release();await pool.end()
  if(previousFinalization===undefined)delete process.env.PAYROLL_FINALIZATION_ENABLED;else process.env.PAYROLL_FINALIZATION_ENABLED=previousFinalization
  if(previousDayScope===undefined)delete process.env.PAYROLL_DAY_SHIFT_ONLY;else process.env.PAYROLL_DAY_SHIFT_ONLY=previousDayScope
  if(previousNodeEnv===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=previousNodeEnv
 }
})
