<script setup>
import {computed,onMounted,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import PayrollShiftTabs from '@/components/payroll/PayrollShiftTabs.vue'
import {payrollShift} from '@/utils/payrollScope'
import {profileGaps,profileReady} from '@/utils/payRun'
import {getPayrollProfiles,getPayrollProfileHistory,updatePayrollProfile} from '@/services/api'
import {useToastStore} from '@/stores/toastStore'
import PageHeader from '@/components/ui/PageHeader.vue'
import AppButton from '@/components/ui/AppButton.vue'
const route=useRoute(),toast=useToastStore(),profiles=ref([]),selected=ref(null),history=ref([]),search=ref(''),busy=ref(false),error=ref('')
const router=useRouter(),shift=ref(payrollShift(route.query.shift))
watch(()=>route.query.shift,value=>{if(value!==undefined)shift.value=payrollShift(value)})
watch(shift,async()=>{selected.value=null;history.value=[];profiles.value=[];await router.replace({query:{...route.query,shift:shift.value}});await load()})
const today=new Date(Date.now()+8*3600000).toISOString().slice(0,10)
const form=ref({monthlyBasicSalary:'',monthlyCola:0,biometricPersonId:'',effectiveFrom:today,workStartTime:'09:00',workEndTime:'18:00',workdays:[1,2,3,4,5]})
const overnight=computed(()=>form.value.workEndTime<form.value.workStartTime)
function useEmployeeShift(){const night=String(selected.value?.shift).toLowerCase()==='night';form.value.workStartTime=night?'21:00':'09:00';form.value.workEndTime=night?'06:00':'18:00'}
const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat']
const filtered=computed(()=>profiles.value.filter(p=>`${p.first_name} ${p.last_name} ${p.employee_code} ${p.biometric_person_id}`.toLowerCase().includes(search.value.toLowerCase())))
async function load(){const selectedShift=shift.value;try{const people=await getPayrollProfiles(selectedShift);if(selectedShift===shift.value)profiles.value=people}catch(e){error.value=e.message}}
async function choose(p){error.value='';history.value=[];selected.value=p;form.value={monthlyBasicSalary:p.monthly_basic_salary??'',monthlyCola:p.monthly_cola??0,biometricPersonId:p.biometric_person_id||'',effectiveFrom:today,workStartTime:String(p.work_start_time||(String(p.shift).toLowerCase()==='night'?'21:00':'09:00')).slice(0,5),workEndTime:String(p.work_end_time||(String(p.shift).toLowerCase()==='night'?'06:00':'18:00')).slice(0,5),workdays:[...(p.workdays||[1,2,3,4,5])]};try{history.value=await getPayrollProfileHistory(p.employee_id)}catch(e){error.value=e.message}}
async function save(){busy.value=true;error.value='';try{await updatePayrollProfile(selected.value.employee_id,{...form.value,unpaidBreakMinutes:60,dailyRateDivisor:261});await load();const updated=profiles.value.find(p=>p.employee_id===selected.value.employee_id);if(updated)await choose(updated);else{selected.value=null;history.value=[]}toast.success('Effective-dated pay and schedule saved')}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(async()=>{try{await load();if(route.query.employee){const p=profiles.value.find(p=>String(p.employee_id)===String(route.query.employee));if(p)await choose(p)}}catch(e){error.value=e.message}})
</script>
<template>
 <div class="space-y-6"><PageHeader title="Pay & schedules"><template v-if="String(route.query.returnTo||'').startsWith('/payroll')" #actions><RouterLink :to="String(route.query.returnTo)" class="text-sm font-semibold text-primary-300 hover:underline">{{String(route.query.returnTo)==='/payroll'?'Back to Payroll':'Back to pay run'}} →</RouterLink></template></PageHeader>
  <PayrollShiftTabs v-model="shift" :disabled="busy" />
  <p v-if="error" role="alert" class="rounded-lg border border-red-800 p-3 text-red-200">{{error}}</p>
  <div class="grid gap-6 lg:grid-cols-3"><section class="rounded-xl border border-gray-800 p-4"><input v-model="search" class="form-control" placeholder="Name, Employee ID, Attendance ID" aria-label="Search pay profiles"><div class="mt-3 max-h-[36rem] overflow-auto"><button v-for="p in filtered" :key="p.employee_id" class="block w-full rounded-lg border-b border-gray-800 p-3 text-left" :class="selected?.employee_id===p.employee_id?'bg-primary-950/40':''" @click="choose(p)"><p class="font-medium">{{p.first_name}} {{p.last_name}}</p><p class="text-xs text-gray-400">Employee ID {{p.employee_code}} · Attendance ID {{p.biometric_person_id||'Not mapped'}}</p><p class="mt-1 text-xs" :class="profileReady(p)?'text-emerald-300':'text-amber-300'">{{profileReady(p)?'Ready for payroll':`Needs ${profileGaps(p).map(gap=>gap==='Attendance ID'?gap:gap.toLowerCase()).join(', ')}`}}</p></button></div></section>
  <section v-if="selected" class="space-y-5 rounded-xl border border-gray-800 p-5 lg:col-span-2"><div><h2 class="font-semibold">{{selected.first_name}} {{selected.last_name}}</h2><p class="text-sm text-gray-400">Employee ID: {{selected.employee_code}} · {{String(selected.shift).toLowerCase()==='night'?'Night':'Day'}} shift in Employee Management</p></div>
   <div class="rounded-lg border border-primary-800/40 bg-primary-950/20 p-3 text-sm"><p class="font-medium">{{overnight?'Night shift · clock-out is the next day':'Day shift'}}</p><p class="mt-1 text-gray-400">{{overnight?'9 PM–6 AM · unpaid break 1–2 AM':'9 AM–6 PM · unpaid break 1–2 PM'}}. Night differential is calculated automatically at 10% for actual paid work from 10 PM–6 AM.</p><button v-if="(String(selected.shift).toLowerCase()==='night')!==overnight" type="button" class="mt-2 underline text-primary-300" @click="useEmployeeShift">Use the shift from Employee Management</button></div>
   <form class="grid gap-4 sm:grid-cols-2" @submit.prevent="save"><label class="text-sm">Biometric Attendance ID<input v-model="form.biometricPersonId" class="form-control mt-1" maxlength="80" placeholder="Preserve leading zeroes"></label><label class="text-sm">Effective from<input v-model="form.effectiveFrom" type="date" required class="form-control mt-1"></label><label class="text-sm">Monthly basic salary<input v-model.number="form.monthlyBasicSalary" type="number" min="0.01" step="0.01" required class="form-control mt-1"></label><label class="text-sm">Monthly COLA<input v-model.number="form.monthlyCola" type="number" min="0" step="0.01" class="form-control mt-1"></label><label class="text-sm">Work starts<input v-model="form.workStartTime" type="time" required class="form-control mt-1"></label><label class="text-sm">Work ends{{overnight?' (next day)':''}}<input v-model="form.workEndTime" type="time" required class="form-control mt-1"></label><fieldset class="sm:col-span-2"><legend class="text-sm">Scheduled workdays</legend><div class="mt-2 flex gap-3"><label v-for="(day,index) in days" :key="day" class="text-sm"><input v-model="form.workdays" type="checkbox" :value="index"> {{day}}</label></div></fieldset><p class="text-xs text-gray-400 sm:col-span-2">Use the date these values actually took effect. Finalized payroll is retained; changes affecting finalized periods need a future effective date and an adjustment. Schedules use eight paid hours and a fixed one-hour unpaid break. Overnight attendance belongs to the date the shift starts; paid leave does not earn night differential.</p><AppButton type="submit" :loading="busy">Save pay & schedule</AppButton></form>
   <div><h3 class="font-semibold">Compensation and schedule history</h3><div class="mt-3 overflow-auto"><table class="w-full text-left text-sm"><thead class="text-xs text-gray-400"><tr><th class="p-2">Effective dates</th><th class="p-2">Monthly basic</th><th class="p-2">COLA</th><th class="p-2">Schedule</th></tr></thead><tbody><tr v-for="p in history" :key="p.id" class="border-t border-gray-800"><td class="p-2">{{p.effective_from}} – {{p.effective_to||'Current'}}</td><td class="p-2">{{Number(p.monthly_basic_salary).toFixed(2)}}</td><td class="p-2">{{Number(p.monthly_cola).toFixed(2)}}</td><td class="p-2">{{p.work_start_time}} – {{p.work_end_time}}</td></tr></tbody></table><p v-if="!history.length" class="text-sm text-gray-500">No actual salary has been entered yet.</p></div></div>
  </section><p v-else class="p-5 text-gray-400 lg:col-span-2">Choose an employee to configure their pay and schedule.</p></div>
 </div>
</template>
